// <auto-generated />
using System;
using MathInsight.Modules.Learning_Lecture.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MathInsight.Modules.Learning_Lecture.Migrations
{
    [DbContext(typeof(LearningDbContext))]
    partial class LearningDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MathInsight.Modules.Learning_Lecture.Entities.AccountProfileView", b =>
                {
                    b.Property<string>("AccountId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("AccountID");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AccountId");

                    b.ToTable((string)null);

                    b.ToView("AccountProfileView", "dbo");
                });

            modelBuilder.Entity("MathInsight.Modules.Learning_Lecture.Entities.DiscussionAnswer", b =>
                {
                    b.Property<string>("DiscussionAnswerId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiscussionQuestionId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("ModerationReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("DiscussionAnswerId");

                    b.HasIndex("DiscussionQuestionId");

                    b.ToTable("DiscussionAnswer", (string)null);
                });

            modelBuilder.Entity("MathInsight.Modules.Learning_Lecture.Entities.DiscussionQuestion", b =>
                {
                    b.Property<string>("DiscussionQuestionId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LectureId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("ModerationReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("DiscussionQuestionId");

                    b.HasIndex("LectureId");

                    b.ToTable("DiscussionQuestion", (string)null);
                });

            modelBuilder.Entity("MathInsight.Modules.Learning_Lecture.Entities.DiscussionReport", b =>
                {
                    b.Property<string>("ReportId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiscussionAnswerId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("DiscussionQuestionId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("ReportReason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReporterAccountId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime?>("ResolvedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResolverAccountId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("ResolvedByAccountID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.HasKey("ReportId");

                    b.HasIndex("DiscussionAnswerId");

                    b.HasIndex("DiscussionQuestionId");

                    b.ToTable("DiscussionReport", null, t =>
                        {
                            t.HasCheckConstraint("CK_DiscussionReport_Target", "([DiscussionQuestionId] IS NOT NULL AND [DiscussionAnswerId] IS NULL) OR ([DiscussionQuestionId] IS NULL AND [DiscussionAnswerId] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("MathInsight.Modules.Learning_Lecture.Entities.Lecture", b =>
                {
                    b.Property<string>("LectureId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Likes")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Draft");

                    b.Property<string>("TagId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("TeacherId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("LectureId");

                    b.HasIndex("Status", "TagId");

                    b.ToTable("Lecture", (string)null);
                });

            modelBuilder.Entity("MathInsight.Modules.Learning_Lecture.Entities.LectureLike", b =>
                {
                    b.Property<string>("LectureId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("StudentId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("LectureId", "StudentId");

                    b.ToTable("LectureLike", (string)null);
                });

            modelBuilder.Entity("MathInsight.Modules.Learning_Lecture.Entities.LectureMaterial", b =>
                {
                    b.Property<string>("LectureId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("MaterialId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.HasKey("LectureId", "MaterialId");

                    b.HasIndex("MaterialId");

                    b.ToTable("LectureMaterial", (string)null);
                });

            modelBuilder.Entity("MathInsight.Modules.Learning_Lecture.Entities.Material", b =>
                {
                    b.Property<string>("MaterialId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.Property<string>("TeacherId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime>("UploadedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("MaterialId");

                    b.ToTable("Material", (string)null);
                });

            modelBuilder.Entity("MathInsight.Modules.Learning_Lecture.Entities.TagTopicReadOnly", b =>
                {
                    b.Property<string>("TagId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("TagID");

                    b.Property<int>("Grade")
                        .HasColumnType("int")
                        .HasColumnName("Grade");

                    b.Property<string>("ParentTagId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("ParentTagID");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TagName");

                    b.HasKey("TagId");

                    b.ToTable("TagTopic", (string)null);
                });

            modelBuilder.Entity("MathInsight.Modules.Learning_Lecture.Entities.DiscussionAnswer", b =>
                {
                    b.HasOne("MathInsight.Modules.Learning_Lecture.Entities.DiscussionQuestion", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("DiscussionQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("MathInsight.Modules.Learning_Lecture.Entities.DiscussionQuestion", b =>
                {
                    b.HasOne("MathInsight.Modules.Learning_Lecture.Entities.Lecture", "Lecture")
                        .WithMany("DiscussionQuestions")
                        .HasForeignKey("LectureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lecture");
                });

            modelBuilder.Entity("MathInsight.Modules.Learning_Lecture.Entities.DiscussionReport", b =>
                {
                    b.HasOne("MathInsight.Modules.Learning_Lecture.Entities.DiscussionAnswer", "Answer")
                        .WithMany("Reports")
                        .HasForeignKey("DiscussionAnswerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MathInsight.Modules.Learning_Lecture.Entities.DiscussionQuestion", "Question")
                        .WithMany("Reports")
                        .HasForeignKey("DiscussionQuestionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Answer");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("MathInsight.Modules.Learning_Lecture.Entities.LectureLike", b =>
                {
                    b.HasOne("MathInsight.Modules.Learning_Lecture.Entities.Lecture", "Lecture")
                        .WithMany("LectureLikes")
                        .HasForeignKey("LectureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lecture");
                });

            modelBuilder.Entity("MathInsight.Modules.Learning_Lecture.Entities.LectureMaterial", b =>
                {
                    b.HasOne("MathInsight.Modules.Learning_Lecture.Entities.Lecture", "Lecture")
                        .WithMany("LectureMaterials")
                        .HasForeignKey("LectureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MathInsight.Modules.Learning_Lecture.Entities.Material", "Material")
                        .WithMany("LectureMaterials")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lecture");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("MathInsight.Modules.Learning_Lecture.Entities.DiscussionAnswer", b =>
                {
                    b.Navigation("Reports");
                });

            modelBuilder.Entity("MathInsight.Modules.Learning_Lecture.Entities.DiscussionQuestion", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Reports");
                });

            modelBuilder.Entity("MathInsight.Modules.Learning_Lecture.Entities.Lecture", b =>
                {
                    b.Navigation("DiscussionQuestions");

                    b.Navigation("LectureLikes");

                    b.Navigation("LectureMaterials");
                });

            modelBuilder.Entity("MathInsight.Modules.Learning_Lecture.Entities.Material", b =>
                {
                    b.Navigation("LectureMaterials");
                });
#pragma warning restore 612, 618
        }
    }
}
