/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#1a1b22",
        "inverse-on-surface": "#eff0fa",
        "primary": "#0058be",
        "on-secondary-container": "#63646c",
        "inverse-primary": "#adc6ff",
        "on-tertiary-container": "#fffbff",
        "primary-fixed-dim": "#adc6ff",
        "surface-container-low": "#f2f3fd",
        "secondary-container": "#e3e1ec",
        "on-error": "#ffffff",
        "secondary": "#5d5e66",
        "tertiary": "#924700",
        "surface-bright": "#f9f9ff",
        "outline-variant": "#c2c6d6",
        "background": "#f9f9ff",
        "error-container": "#ffdad6",
        "primary-container": "#2170e4",
        "tertiary-fixed": "#ffdcc6",
        "amber-warning": "#F59E0B",
        "on-secondary": "#ffffff",
        "whisper-border": "rgba(226, 232, 240, 0.5)",
        "emerald-success": "#10B981",
        "on-tertiary-fixed-variant": "#723600",
        "error": "#ba1a1a",
        "surface-dim": "#d8d9e3",
        "secondary-fixed": "#e3e1ec",
        "inverse-surface": "#2e3038",
        "on-tertiary-fixed": "#311400",
        "on-surface-variant": "#424754",
        "canvas-white": "#F9FAFB",
        "on-primary": "#ffffff",
        "deep-rose": "#E11D48",
        "on-primary-container": "#fefcff",
        "surface-variant": "#e1e2ec",
        "charcoal-ink": "#18181B",
        "on-background": "#191b23",
        "on-primary-fixed": "#001a42",
        "surface-container": "#ecedf7",
        "tertiary-fixed-dim": "#ffb786",
        "on-error-container": "#93000a",
        "on-secondary-fixed-variant": "#46464e",
        "surface": "#f9f9ff",
        "surface-container-highest": "#e1e2ec",
        "surface-tint": "#005ac2",
        "on-tertiary": "#ffffff",
        "primary-fixed": "#d8e2ff",
        "surface-container-lowest": "#ffffff",
        "outline": "#727785",
        "surface-container-high": "#e6e7f2",
        "pure-surface": "#FFFFFF",
        "on-surface": "#191b23",
        "on-primary-fixed-variant": "#004395",
        "tertiary-container": "#b75b00",
        "secondary-fixed-dim": "#c6c5cf"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
        "2.5xl": "2.5rem"
      },
      spacing: {
        "gutter": "1.5rem",
        "sidebar-width": "280px",
        "header-height": "64px",
        "density-unit": "4px",
        "container-margin": "2rem"
      },
      fontFamily: {
        body: ["Geist", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"]
      }
    },
  },
  plugins: [],
}
