using System;

namespace MathInsight.Modules.TestGen.Persistence.Entities;

/// <summary>
/// TestQuestion composite key entity (generated by TestGen, read by Testing module).
/// Maps to SQL table: TestQuestion.
/// </summary>
public class TestQuestion
{
    public Guid TestId { get; set; }
    public Guid QuestionId { get; set; }
    public int QuestionOrder { get; set; }
}
