namespace MathInsight.Modules.TestGen.Persistence.Entities;

/// <summary>
/// Test entity (generated by TestGen, read by Testing module).
/// Maps to SQL table: Test.
/// </summary>
public class Test
{
    public string TestId { get; set; } = string.Empty;
    public string? BlueprintId { get; set; }
    public string TestStatus { get; set; } = "Active";
    public string TestMode { get; set; } = "BlueprintExam";
    public string? GeneratedForStudentId { get; set; }
    public string GeneratedBy { get; set; } = "System";
    public string TestName { get; set; } = string.Empty;
    public string? TestCode { get; set; }
    public int DurationMinutes { get; set; }
    public int TotalQuestions { get; set; }
    public DateTime CreatedTime { get; set; } = DateTime.UtcNow;

    public Blueprint? Blueprint { get; set; }
    public ICollection<TestQuestion> Questions { get; set; } = new List<TestQuestion>();
}
