using System;

namespace MathInsight.Modules.TestGen.Persistence.Entities;

/// <summary>
/// Test entity (generated by TestGen, read by Testing module).
/// Maps to SQL table: Test.
/// </summary>
public class Test
{
    public Guid TestId { get; set; }
    public Guid? BlueprintId { get; set; }
    
    /// <summary>Practice | Exam</summary>
    public string TestFormat { get; set; } = "Exam";
    
    public Guid? GeneratedForStudentId { get; set; }
    public string GeneratedBy { get; set; } = "System";
    public string TestName { get; set; } = string.Empty;
    public string? TestCode { get; set; }
    public int DurationMinutes { get; set; }
    public int TotalQuestions { get; set; }
    
    /// <summary>ACTIVE | ARCHIVED</summary>
    public string TestStatus { get; set; } = "ACTIVE";
    
    public DateTime CreatedTime { get; set; } = DateTime.UtcNow;
}
